# Basic Auth Secret  
# Username: arad
# Password: arad1980

apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-auth
  namespace: bitcoin-app
type: Opaque
data:
  # This is base64 encoded: arad:arad1980
  auth: YXJhZDphcmFkMTk4MA==