# Basic Auth Secret
# Username: demo
# Password: bitcoin2024!

apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-auth
  namespace: default
type: Opaque
data:
  # This is base64 encoded: demo:$2b$10$hBijBMBTT8G6F.QRw.pI.eL5vQRxmkAWjF5a5.A8d1k1.E8J2VQ1C
  # Original: demo:bitcoin2024!
  auth: ZGVtbzokMmIkMTAkaEJpakJNQlRUOEc2Ri5RUnducEkuZUw1dlFSeG1rQVdqRjVhNS5BOHF3a1xFOEoyVlExQwo=