apiVersion: v1
kind: Service
metadata:
  name: bitcoin-app-loadbalancer
  namespace: bitcoin-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-aks-free-tier"
spec:
  type: LoadBalancer
  selector:
    app: service-a  # מחבר לאפליקציה שלנו
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  # יוצר IP חיצוני באזור