apiVersion: v1
kind: Service
metadata:
  name: bitcoin-app-nodeport
  namespace: bitcoin-app
spec:
  type: NodePort
  selector:
    app: service-a  # מחבר לאפליקציה שלנו
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080  # יהיה זמין על פורט 30080
      protocol: TCP